function umha(){
  document.write(
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Segunda-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Inglês</td></td></tr>" + "<tr><td>08:10-08:50<td>Artes</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Língua Portuguesa</td></td></tr>" + "<tr><td>09:40-10:20<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>História</td></td></tr>" + "<tr><td>11:10-11:50<td>Biologia</td></td></tr>" + "<tr><td>11:50-12:30<td>Física</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Terça-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Matemática</td></td></tr>" + "<tr><td>08:10-08:50<td>Química</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Biologia</td></td></tr>" + "<tr><td>09:40-10:20<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>11:10-11:50<td>Geografia</td></td></tr>" + "<tr><td>11:50-12:30<td>Artes</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quarta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>*****</td></td></tr>" + "<tr><td>08:10-08:50<td>Inglês</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Física</td></td></tr>" + "<tr><td>09:40-10:20<td>História</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>11:10-11:50<td>Língua Portuguesa</td></td></tr>" + "<tr><td>11:50-12:30<td>Química</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quinta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Matemática</td></td></tr>" + "<tr><td>08:10-08:50<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Física</td></td></tr>" + "<tr><td>09:40-10:20<td>Geografia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>11:10-11:50<td>Biologia</td></td></tr>" + "<tr><td>11:50-12:30<td>Projeto de vida</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Sexta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Geografia</td></td></tr>" + "<tr><td>08:10-08:50<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Matemática</td></td></tr>" + "<tr><td>09:40-10:20<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Química</td></td></tr>" + "<tr><td>11:10-11:50<td>História</td></td></tr>" + "<tr><td>11:50-12:30<td>Educação Física</td></td></tr>" + "</table>"
    )
}

function doisha(){
    document.write(
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Segunda-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Artes</td></td></tr>" + "<tr><td>08:10-08:50<td>Inglês</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>História</td></td></tr>" + "<tr><td>09:40-10:20<td>Biologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>11:10-11:50<td>Língua Portuguesa</td></td></tr>" + "<tr><td>11:50-12:30<td>Projeto de vida</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Terça-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Química</td></td></tr>" + "<tr><td>08:10-08:50<td>Artes</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Matemática</td></td></tr>" + "<tr><td>09:40-10:20<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Geografia</td></td></tr>" + "<tr><td>11:10-11:50<td>Biologia</td></td></tr>" + "<tr><td>11:50-12:30<td>*****</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quarta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Química</td></td></tr>" + "<tr><td>08:10-08:50<td>Física</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Inglês</td></td></tr>" + "<tr><td>09:40-10:20<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>História</td></td></tr>" + "<tr><td>11:10-11:50<td>Matemática</td></td></tr>" + "<tr><td>11:50-12:30<td>Educação Física</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quinta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Geografia</td></td></tr>" + "<tr><td>08:10-08:50<td>Física</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Matemática</td></td></tr>" + "<tr><td>09:40-10:20<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Biologia</td></td></tr>" + "<tr><td>11:10-11:50<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>11:50-12:30<td>Língua Portuguesa</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Sexta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Física</td></td></tr>" + "<tr><td>08:10-08:50<td>Geografia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>09:40-10:20<td>História</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Matemática</td></td></tr>" + "<tr><td>11:10-11:50<td>Química</td></td></tr>" + "<tr><td>11:50-12:30<td>Língua Portuguesa</td></td></tr>" + "</table>"
    )
}

function tresha(){
    document.write(
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Segunda-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>08:10-08:50<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Biologia</td></td></tr>" + "<tr><td>09:40-10:20<td>Inglês</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Inglês</td></td></tr>" + "<tr><td>11:10-11:50<td>História</td></td></tr>" + "<tr><td>11:50-12:30<td>Artes</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Terça-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>*****</td></td></tr>" + "<tr><td>08:10-08:50<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Língua Portuguesa</td></td></tr>" + "<tr><td>09:40-10:20<td>Biologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Matemática</td></td></tr>" + "<tr><td>11:10-11:50<td>Artes</td></td></tr>" + "<tr><td>11:50-12:30<td>Química</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quarta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Física</td></td></tr>" + "<tr><td>08:10-08:50<td>Química</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Língua Portuguesa</td></td></tr>" + "<tr><td>09:40-10:20<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Matemática</td></td></tr>" + "<tr><td>11:10-11:50<td>História</td></td></tr>" + "<tr><td>11:50-12:30<td>Projeto de vida</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quinta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Física</td></td></tr>" + "<tr><td>08:10-08:50<td>Geografia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Geografia</td></td></tr>" + "<tr><td>09:40-10:20<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>11:10-11:50<td>Matemática</td></td></tr>" + "<tr><td>11:50-12:30<td>Biologia</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Sexta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>07:30-08:10<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>08:10-08:50<td>Física</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>09:00-09:40<td>Geografia</td></td></tr>" + "<tr><td>09:40-10:20<td>Química</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>10:30-11:10<td>História</td></td></tr>" + "<tr><td>11:10-11:50<td>Matemática</td></td></tr>" + "<tr><td>11:50-12:30<td>Educação Física</td></td></tr>" + "</table>"
    )
}