function umhb(){
  document.write(
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Segunda-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>Educação Física</td></td></tr>" + "<tr><td>14:10-14:50<td>ADW</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>ADW</td></td></tr>" + "<tr><td>15:40-16:10<td>Física</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Biologia</td></td></tr>" + "<tr><td>17:10-17:50<td>Inglês</td></td></tr>" + "<tr><td>17:50-18:30<td>Química</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Terça-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>14:10-14:50<td>História</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Biologia</td></td></tr>" + "<tr><td>15:40-16:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>ADW</td></td></tr>" + "<tr><td>17:10-17:50<td>ADW</td></td></tr>" + "<tr><td>17:50-18:30<td>ADW</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quarta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>Geografia</td></td></tr>" + "<tr><td>14:10-14:50<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Língua Portuguesa</td></td></tr>" + "<tr><td>15:40-16:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>ADW</td></td></tr>" + "<tr><td>17:10-17:50<td>ADW</td></td></tr>" + "<tr><td>17:50-18:30<td>ADW</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quinta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>ADW</td></td></tr>" + "<tr><td>14:10-14:50<td>ADW</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>15:40-16:10<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Química</td></td></tr>" + "<tr><td>17:10-17:50<td>Língua Portuguesa</td></td></tr>" + "<tr><td>17:50-18:30<td>Projeto de vida</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Sexta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>ADW</td></td></tr>" + "<tr><td>14:10-14:50<td>ADW</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Matemática</td></td></tr>" + "<tr><td>15:40-16:10<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Física</td></td></tr>" + "<tr><td>17:10-17:50<td>Geografia</td></td></tr>" + "<tr><td>17:50-18:30<td>História</td></td></tr>" + "</table>"
    )
}

function doishb(){
    document.write(
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Segunda-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>STI</td></td></tr>" + "<tr><td>14:10-14:50<td>STI</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Física</td></td></tr>" + "<tr><td>15:40-16:10<td>Biologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Química</td></td></tr>" + "<tr><td>17:10-17:50<td>Matemática</td></td></tr>" + "<tr><td>17:50-18:30<td>Inglês</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Terça-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:20-14:00<td>Projeto de vida</td></td></tr>" + "<tr><td>14:10-14:50<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>História</td></td></tr>" + "<tr><td>15:40-16:10<td>Biologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>17:10-17:50<td>STI</td></td></tr>" + "<tr><td>17:50-18:30<td>STI</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quarta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>STI</td></td></tr>" + "<tr><td>14:10-14:50<td>STI</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Geografia</td></td></tr>" + "<tr><td>15:40-16:10<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Matemática</td></td></tr>" + "<tr><td>17:10-17:50<td>Língua Portuguesa</td></td></tr>" + "<tr><td>17:50-18:30<td>Língua Portuguesa</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quinta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>Educação Física</td></td></tr>" + "<tr><td>14:10-14:50<td>Matemática</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Química</td></td></tr>" + "<tr><td>15:40-16:10<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>17:10-17:50<td>STI</td></td></tr>" + "<tr><td>17:50-18:30<td>STI</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Sexta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>STI</td></td></tr>" + "<tr><td>14:10-14:50<td>STI</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>STI</td></td></tr>" + "<tr><td>15:40-16:10<td>STI</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>História</td></td></tr>" + "<tr><td>17:10-17:50<td>Física</td></td></tr>" + "<tr><td>17:50-18:30<td>Geografia</td></td></tr>" + "</table>"
    )
}

function treshb(){
    document.write(
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Segunda-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>IS</td></td></tr>" + "<tr><td>14:10-14:50<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>IS</td></td></tr>" + "<tr><td>15:40-16:10<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Física</td></td></tr>" + "<tr><td>17:10-17:50<td>Química</td></td></tr>" + "<tr><td>17:50-18:30<td>Biologia</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Terça-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>IS</td></td></tr>" + "<tr><td>14:10-14:50<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>IS</td></td></tr>" + "<tr><td>15:40-16:10<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Biologia</td></td></tr>" + "<tr><td>17:10-17:50<td>Língua Portuguesa</td></td></tr>" + "<tr><td>17:50-18:30<td>Língua Portuguesa</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quarta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>IS</td></td></tr>" + "<tr><td>14:10-14:50<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>IS</td></td></tr>" + "<tr><td>15:40-16:10<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Língua Portuguesa</td></td></tr>" + "<tr><td>17:10-17:50<td>Matemática</td></td></tr>" + "<tr><td>17:50-18:30<td>Projeto de vida</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Quinta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>Química</td></td></tr>" + "<tr><td>14:10-14:50<td>Filosofia/Sociologia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>Língua Portuguesa</td></td></tr>" + "<tr><td>15:40-16:10<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Artes</td></td></tr>" + "<tr><td>17:10-17:50<td>IS</td></td></tr>" + "<tr><td>17:50-18:30<td>IS</td></td></tr>" + "</table>"
    +
    "<h3 style='font-family: Arial, Helvetica, sans-serif'>Sexta-Feira</h3>" + "<table style='font-family: Arial, Helvetica, sans-serif'>" + "<tr><td>13:30-14:10<td>IS</td></td></tr>" + "<tr><td>14:10-14:50<td>IS</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>15:00-15:40<td>História</td></td></tr>" + "<tr><td>15:40-16:10<td>Geografia</td></td></tr>" + "<tr><td>Intervalo</td></tr>" + "<tr><td>16:30-17:10<td>Matemática</td></td></tr>" + "<tr><td>17:10-17:50<td>Matemática</td></td></tr>" + "<tr><td>17:50-18:30<td>Física</td></td></tr>" + "</table>"
    )
}